// Root layout — wraps every page with fonts, providers, nav, cursor, and curtain.
// Also carries the site-wide search/share metadata and structured data.
// Edit studio details in lib/site.js, not here.

import "@/styles/globals.css";
import { SITE } from "@/lib/site";
import { NavigationProvider } from "@/lib/navigation";
import { Nav } from "@/components/Nav";
import { CustomCursor, PageCurtain } from "@/components/Anim";

const TITLE = `${SITE.name} — Video, Flyers, DJ EPKs & Websites · ${SITE.city}`;

export const metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: TITLE,
    template: `%s — ${SITE.name}`,
  },
  description: SITE.description,
  keywords: SITE.keywords,
  applicationName: SITE.name,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: SITE.name,
    locale: "en_GB",
    url: "/",
    title: TITLE,
    description: SITE.tagline + " " + SITE.description,
    // The share image itself is generated by app/opengraph-image.jsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: SITE.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#0A0A0A",
};

// Structured data — tells search engines what the studio is, where it is,
// and what it makes. One Organization node + one WebSite node.
const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": ["Organization", "ProfessionalService"],
      "@id": `${SITE.url}/#organization`,
      name: SITE.name,
      alternateName: SITE.nameJp,
      url: SITE.url,
      logo: `${SITE.url}/apple-icon`,
      image: `${SITE.url}/opengraph-image`,
      description: SITE.description,
      slogan: SITE.tagline,
      email: SITE.email,
      sameAs: [SITE.instagram],
      address: {
        "@type": "PostalAddress",
        addressLocality: SITE.city,
        addressCountry: SITE.countryCode,
      },
      areaServed: ["Osaka", "Japan", "United Kingdom", "United States", "Worldwide"],
      knowsLanguage: ["en", "ja"],
      makesOffer: [
        "Video production & motion design",
        "Event flyer & social media design",
        "DJ EPK & press kit design",
        "Website design",
        "Menu & print design",
        "Brand identity",
      ].map((name) => ({
        "@type": "Offer",
        itemOffered: { "@type": "Service", name },
      })),
    },
    {
      "@type": "WebSite",
      "@id": `${SITE.url}/#website`,
      url: SITE.url,
      name: SITE.name,
      publisher: { "@id": `${SITE.url}/#organization` },
      inLanguage: "en",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://player.vimeo.com" />
        <link rel="dns-prefetch" href="https://i.vimeocdn.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Geist:wght@300;400;500;600;700;800&family=Space+Mono:ital,wght@0,400;0,700;1,400&family=Newsreader:ital,wght@1,200;1,300;1,400&family=Noto+Sans+JP:wght@400;500;700&display=swap"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      </head>
      <body>
        <NavigationProvider>
          <CustomCursor />
          <PageCurtain />
          <Nav />
          {children}
        </NavigationProvider>
      </body>
    </html>
  );
}
